// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/dashboard-cinematic.scene.json";
export const sceneModules = {
  "src/flute/scenes/dashboard-cinematic.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/dashboard-cinematic.tsx": () => import("./scenes/dashboard-cinematic"),
};
